[tool.poetry]
name = "homework2"
version = "0.1.0"
description = ""
authors = ["Даниил Ермилов <yndx-daniel-ocean@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[tool.poetry.group.dev.dependencies]
isort = "^6.0.0"
black = "^25.1.0"
pytest = "^8.3.4"
flake8 = "^7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
